// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// scatter_assign_mat
void scatter_assign_mat(List geno_list, IntegerVector rows, IntegerVector cols, List vals);
RcppExport SEXP _VCFArrow_scatter_assign_mat(SEXP geno_listSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP valsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type geno_list(geno_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< List >::type vals(valsSEXP);
    scatter_assign_mat(geno_list, rows, cols, vals);
    return R_NilValue;
END_RCPP
}
// scatter_assign_vec
void scatter_assign_vec(List geno_list, IntegerVector rows, IntegerVector cols, CharacterVector vals);
RcppExport SEXP _VCFArrow_scatter_assign_vec(SEXP geno_listSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP valsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type geno_list(geno_listSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vals(valsSEXP);
    scatter_assign_vec(geno_list, rows, cols, vals);
    return R_NilValue;
END_RCPP
}
// parse_vcf_cpp
List parse_vcf_cpp(CharacterVector lines, int nsamples);
RcppExport SEXP _VCFArrow_parse_vcf_cpp(SEXP linesSEXP, SEXP nsamplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_vcf_cpp(lines, nsamples));
    return rcpp_result_gen;
END_RCPP
}
// write_smartsnp_header_cpp
void write_smartsnp_header_cpp(const CharacterVector& samples, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_smartsnp_header_cpp(SEXP samplesSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_smartsnp_header_cpp(samples, out_file);
    return R_NilValue;
END_RCPP
}
// write_smartsnp_chunk_cpp
void write_smartsnp_chunk_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_smartsnp_chunk_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_smartsnp_chunk_cpp(a1_mat, a2_mat, out_file);
    return R_NilValue;
END_RCPP
}
// write_structure_cpp
void write_structure_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& samples, const IntegerVector& group_ids, int method_int, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_structure_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP samplesSEXP, SEXP group_idsSEXP, SEXP method_intSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group_ids(group_idsSEXP);
    Rcpp::traits::input_parameter< int >::type method_int(method_intSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_structure_cpp(a1_mat, a2_mat, samples, group_ids, method_int, out_file);
    return R_NilValue;
END_RCPP
}
// write_arlequin_cpp
void write_arlequin_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const CharacterVector& samples, const CharacterVector& group_names, const IntegerVector& group_sizes, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_arlequin_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP samplesSEXP, SEXP group_namesSEXP, SEXP group_sizesSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type group_names(group_namesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group_sizes(group_sizesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_arlequin_cpp(a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, out_file);
    return R_NilValue;
END_RCPP
}
// write_genepop_cpp
void write_genepop_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const CharacterVector& samples, const CharacterVector& group_names, const IntegerVector& group_sizes, const CharacterVector& loci, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_genepop_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP samplesSEXP, SEXP group_namesSEXP, SEXP group_sizesSEXP, SEXP lociSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type group_names(group_namesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group_sizes(group_sizesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type loci(lociSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_genepop_cpp(a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, loci, out_file);
    return R_NilValue;
END_RCPP
}
// write_fineradstructure_header_cpp
void write_fineradstructure_header_cpp(const CharacterVector& samples, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_fineradstructure_header_cpp(SEXP samplesSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_fineradstructure_header_cpp(samples, out_file);
    return R_NilValue;
END_RCPP
}
// write_fineradstructure_chunk_cpp
void write_fineradstructure_chunk_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_fineradstructure_chunk_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_fineradstructure_chunk_cpp(a1_mat, a2_mat, REF, ALT, out_file);
    return R_NilValue;
END_RCPP
}
// write_treemix_header_cpp
void write_treemix_header_cpp(const CharacterVector& pop_names, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_treemix_header_cpp(SEXP pop_namesSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type pop_names(pop_namesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_treemix_header_cpp(pop_names, out_file);
    return R_NilValue;
END_RCPP
}
// write_treemix_chunk_cpp
void write_treemix_chunk_cpp(const IntegerMatrix& ref_mat, const IntegerMatrix& alt_mat, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_treemix_chunk_cpp(SEXP ref_matSEXP, SEXP alt_matSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ref_mat(ref_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type alt_mat(alt_matSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_treemix_chunk_cpp(ref_mat, alt_mat, out_file);
    return R_NilValue;
END_RCPP
}
// write_bayescan_cpp
void write_bayescan_cpp(const IntegerMatrix& ref_mat, const IntegerMatrix& alt_mat, const IntegerMatrix& n_obs_mat, const CharacterVector& pop_names, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_bayescan_cpp(SEXP ref_matSEXP, SEXP alt_matSEXP, SEXP n_obs_matSEXP, SEXP pop_namesSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ref_mat(ref_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type alt_mat(alt_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type n_obs_mat(n_obs_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type pop_names(pop_namesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_bayescan_cpp(ref_mat, alt_mat, n_obs_mat, pop_names, out_file);
    return R_NilValue;
END_RCPP
}
// write_bayesass_cpp
void write_bayesass_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const CharacterVector& samples, const CharacterVector& group_names, const IntegerVector& group_sizes, const CharacterVector& loci, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_bayesass_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP samplesSEXP, SEXP group_namesSEXP, SEXP group_sizesSEXP, SEXP lociSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type group_names(group_namesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type group_sizes(group_sizesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type loci(lociSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_bayesass_cpp(a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, loci, out_file);
    return R_NilValue;
END_RCPP
}
// write_migrate_cpp
void write_migrate_cpp(const IntegerMatrix& ref_mat, const IntegerMatrix& alt_mat, const IntegerMatrix& n_obs_mat, const CharacterVector& pop_names, const CharacterVector& loci, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_migrate_cpp(SEXP ref_matSEXP, SEXP alt_matSEXP, SEXP n_obs_matSEXP, SEXP pop_namesSEXP, SEXP lociSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type ref_mat(ref_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type alt_mat(alt_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type n_obs_mat(n_obs_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type pop_names(pop_namesSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type loci(lociSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_migrate_cpp(ref_mat, alt_mat, n_obs_mat, pop_names, loci, out_file);
    return R_NilValue;
END_RCPP
}
// write_related_cpp
void write_related_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const CharacterVector& samples, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_related_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP samplesSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_related_cpp(a1_mat, a2_mat, REF, ALT, samples, out_file);
    return R_NilValue;
END_RCPP
}
// write_apparent_cpp
void write_apparent_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const CharacterVector& samples, const std::string& key, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_apparent_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP samplesSEXP, SEXP keySEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type key(keySEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_apparent_cpp(a1_mat, a2_mat, REF, ALT, samples, key, out_file);
    return R_NilValue;
END_RCPP
}
// write_fasta_cpp
void write_fasta_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const CharacterVector& samples, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_fasta_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP samplesSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_fasta_cpp(a1_mat, a2_mat, REF, ALT, samples, out_file);
    return R_NilValue;
END_RCPP
}
// write_nexus_cpp
void write_nexus_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const CharacterVector& REF, const CharacterVector& ALT, const CharacterVector& samples, int format_int, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_nexus_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP REFSEXP, SEXP ALTSEXP, SEXP samplesSEXP, SEXP format_intSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type REF(REFSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type ALT(ALTSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< int >::type format_int(format_intSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_nexus_cpp(a1_mat, a2_mat, REF, ALT, samples, format_int, out_file);
    return R_NilValue;
END_RCPP
}
// write_eigenstrat_geno_header_cpp
void write_eigenstrat_geno_header_cpp(const std::string& out_file);
RcppExport SEXP _VCFArrow_write_eigenstrat_geno_header_cpp(SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_eigenstrat_geno_header_cpp(out_file);
    return R_NilValue;
END_RCPP
}
// write_eigenstrat_chunk_cpp
void write_eigenstrat_chunk_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_eigenstrat_chunk_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_eigenstrat_chunk_cpp(a1_mat, a2_mat, out_file);
    return R_NilValue;
END_RCPP
}
// write_snmf_cpp
void write_snmf_cpp(const IntegerMatrix& a1_mat, const IntegerMatrix& a2_mat, const std::string& out_file);
RcppExport SEXP _VCFArrow_write_snmf_cpp(SEXP a1_matSEXP, SEXP a2_matSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a1_mat(a1_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type a2_mat(a2_matSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    write_snmf_cpp(a1_mat, a2_mat, out_file);
    return R_NilValue;
END_RCPP
}
// write_vcf_chunk_cpp
void write_vcf_chunk_cpp(std::string output_file, CharacterVector chrom, IntegerVector pos, CharacterVector id, CharacterVector ref, CharacterVector alt, CharacterVector qual, CharacterVector filter_col, CharacterVector info, CharacterVector format_col, CharacterVector fmt_vec, int n_samples, bool gzip);
RcppExport SEXP _VCFArrow_write_vcf_chunk_cpp(SEXP output_fileSEXP, SEXP chromSEXP, SEXP posSEXP, SEXP idSEXP, SEXP refSEXP, SEXP altSEXP, SEXP qualSEXP, SEXP filter_colSEXP, SEXP infoSEXP, SEXP format_colSEXP, SEXP fmt_vecSEXP, SEXP n_samplesSEXP, SEXP gzipSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type output_file(output_fileSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type chrom(chromSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos(posSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type id(idSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type ref(refSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type alt(altSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type qual(qualSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type filter_col(filter_colSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type info(infoSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type format_col(format_colSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type fmt_vec(fmt_vecSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type gzip(gzipSEXP);
    write_vcf_chunk_cpp(output_file, chrom, pos, id, ref, alt, qual, filter_col, info, format_col, fmt_vec, n_samples, gzip);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VCFArrow_scatter_assign_mat", (DL_FUNC) &_VCFArrow_scatter_assign_mat, 4},
    {"_VCFArrow_scatter_assign_vec", (DL_FUNC) &_VCFArrow_scatter_assign_vec, 4},
    {"_VCFArrow_parse_vcf_cpp", (DL_FUNC) &_VCFArrow_parse_vcf_cpp, 2},
    {"_VCFArrow_write_smartsnp_header_cpp", (DL_FUNC) &_VCFArrow_write_smartsnp_header_cpp, 2},
    {"_VCFArrow_write_smartsnp_chunk_cpp", (DL_FUNC) &_VCFArrow_write_smartsnp_chunk_cpp, 3},
    {"_VCFArrow_write_structure_cpp", (DL_FUNC) &_VCFArrow_write_structure_cpp, 6},
    {"_VCFArrow_write_arlequin_cpp", (DL_FUNC) &_VCFArrow_write_arlequin_cpp, 8},
    {"_VCFArrow_write_genepop_cpp", (DL_FUNC) &_VCFArrow_write_genepop_cpp, 9},
    {"_VCFArrow_write_fineradstructure_header_cpp", (DL_FUNC) &_VCFArrow_write_fineradstructure_header_cpp, 2},
    {"_VCFArrow_write_fineradstructure_chunk_cpp", (DL_FUNC) &_VCFArrow_write_fineradstructure_chunk_cpp, 5},
    {"_VCFArrow_write_treemix_header_cpp", (DL_FUNC) &_VCFArrow_write_treemix_header_cpp, 2},
    {"_VCFArrow_write_treemix_chunk_cpp", (DL_FUNC) &_VCFArrow_write_treemix_chunk_cpp, 3},
    {"_VCFArrow_write_bayescan_cpp", (DL_FUNC) &_VCFArrow_write_bayescan_cpp, 5},
    {"_VCFArrow_write_bayesass_cpp", (DL_FUNC) &_VCFArrow_write_bayesass_cpp, 9},
    {"_VCFArrow_write_migrate_cpp", (DL_FUNC) &_VCFArrow_write_migrate_cpp, 6},
    {"_VCFArrow_write_related_cpp", (DL_FUNC) &_VCFArrow_write_related_cpp, 6},
    {"_VCFArrow_write_apparent_cpp", (DL_FUNC) &_VCFArrow_write_apparent_cpp, 7},
    {"_VCFArrow_write_fasta_cpp", (DL_FUNC) &_VCFArrow_write_fasta_cpp, 6},
    {"_VCFArrow_write_nexus_cpp", (DL_FUNC) &_VCFArrow_write_nexus_cpp, 7},
    {"_VCFArrow_write_eigenstrat_geno_header_cpp", (DL_FUNC) &_VCFArrow_write_eigenstrat_geno_header_cpp, 1},
    {"_VCFArrow_write_eigenstrat_chunk_cpp", (DL_FUNC) &_VCFArrow_write_eigenstrat_chunk_cpp, 3},
    {"_VCFArrow_write_snmf_cpp", (DL_FUNC) &_VCFArrow_write_snmf_cpp, 3},
    {"_VCFArrow_write_vcf_chunk_cpp", (DL_FUNC) &_VCFArrow_write_vcf_chunk_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_VCFArrow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
