# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scatter_assign_mat <- function(geno_list, rows, cols, vals) {
    invisible(.Call(`_VCFArrow_scatter_assign_mat`, geno_list, rows, cols, vals))
}

scatter_assign_vec <- function(geno_list, rows, cols, vals) {
    invisible(.Call(`_VCFArrow_scatter_assign_vec`, geno_list, rows, cols, vals))
}

vcf_open_cpp <- function(path) {
    .Call(`_VCFArrow_vcf_open_cpp`, path)
}

vcf_close_cpp <- function(handle) {
    invisible(.Call(`_VCFArrow_vcf_close_cpp`, handle))
}

vcf_read_header_cpp <- function(handle) {
    .Call(`_VCFArrow_vcf_read_header_cpp`, handle)
}

vcf_read_chunk_cpp <- function(handle, chunk_size, samples, row_offset) {
    .Call(`_VCFArrow_vcf_read_chunk_cpp`, handle, chunk_size, samples, row_offset)
}

vcf_read_raw_cpp <- function(handle, chunk_size) {
    .Call(`_VCFArrow_vcf_read_raw_cpp`, handle, chunk_size)
}

vcf_parse_raw_cpp <- function(raw, samples, row_offset) {
    .Call(`_VCFArrow_vcf_parse_raw_cpp`, raw, samples, row_offset)
}

sample_counts_cpp <- function(s, a1, a2, dp, n_samples) {
    .Call(`_VCFArrow_sample_counts_cpp`, s, a1, a2, dp, n_samples)
}

match_row_id_cpp <- function(ids, pos) {
    .Call(`_VCFArrow_match_row_id_cpp`, ids, pos)
}

write_smartsnp_header_cpp <- function(samples, out_file) {
    invisible(.Call(`_VCFArrow_write_smartsnp_header_cpp`, samples, out_file))
}

write_smartsnp_chunk_cpp <- function(a1_mat, a2_mat, out_file) {
    invisible(.Call(`_VCFArrow_write_smartsnp_chunk_cpp`, a1_mat, a2_mat, out_file))
}

write_structure_cpp <- function(a1_mat, a2_mat, samples, group_ids, method_int, out_file) {
    invisible(.Call(`_VCFArrow_write_structure_cpp`, a1_mat, a2_mat, samples, group_ids, method_int, out_file))
}

write_arlequin_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, out_file) {
    invisible(.Call(`_VCFArrow_write_arlequin_cpp`, a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, out_file))
}

write_genepop_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, loci, out_file) {
    invisible(.Call(`_VCFArrow_write_genepop_cpp`, a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, loci, out_file))
}

write_fineradstructure_header_cpp <- function(samples, out_file) {
    invisible(.Call(`_VCFArrow_write_fineradstructure_header_cpp`, samples, out_file))
}

write_fineradstructure_chunk_cpp <- function(a1_mat, a2_mat, REF, ALT, out_file) {
    invisible(.Call(`_VCFArrow_write_fineradstructure_chunk_cpp`, a1_mat, a2_mat, REF, ALT, out_file))
}

write_treemix_header_cpp <- function(pop_names, out_file) {
    invisible(.Call(`_VCFArrow_write_treemix_header_cpp`, pop_names, out_file))
}

write_treemix_chunk_cpp <- function(ref_mat, alt_mat, out_file) {
    invisible(.Call(`_VCFArrow_write_treemix_chunk_cpp`, ref_mat, alt_mat, out_file))
}

write_bayescan_cpp <- function(ref_mat, alt_mat, n_obs_mat, pop_names, out_file) {
    invisible(.Call(`_VCFArrow_write_bayescan_cpp`, ref_mat, alt_mat, n_obs_mat, pop_names, out_file))
}

write_bayesass_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, loci, out_file) {
    invisible(.Call(`_VCFArrow_write_bayesass_cpp`, a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, loci, out_file))
}

write_migrate_cpp <- function(ref_mat, alt_mat, n_obs_mat, pop_names, loci, out_file) {
    invisible(.Call(`_VCFArrow_write_migrate_cpp`, ref_mat, alt_mat, n_obs_mat, pop_names, loci, out_file))
}

write_migrate_seq_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, block_labels, out_file) {
    invisible(.Call(`_VCFArrow_write_migrate_seq_cpp`, a1_mat, a2_mat, REF, ALT, samples, group_names, group_sizes, block_labels, out_file))
}

write_related_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, out_file) {
    invisible(.Call(`_VCFArrow_write_related_cpp`, a1_mat, a2_mat, REF, ALT, samples, out_file))
}

write_apparent_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, key, out_file) {
    invisible(.Call(`_VCFArrow_write_apparent_cpp`, a1_mat, a2_mat, REF, ALT, samples, key, out_file))
}

write_fasta_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, out_file) {
    invisible(.Call(`_VCFArrow_write_fasta_cpp`, a1_mat, a2_mat, REF, ALT, samples, out_file))
}

write_nexus_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, format_int, out_file) {
    invisible(.Call(`_VCFArrow_write_nexus_cpp`, a1_mat, a2_mat, REF, ALT, samples, format_int, out_file))
}

write_eigenstrat_geno_header_cpp <- function(out_file) {
    invisible(.Call(`_VCFArrow_write_eigenstrat_geno_header_cpp`, out_file))
}

write_eigenstrat_chunk_cpp <- function(a1_mat, a2_mat, out_file) {
    invisible(.Call(`_VCFArrow_write_eigenstrat_chunk_cpp`, a1_mat, a2_mat, out_file))
}

write_snmf_cpp <- function(a1_mat, a2_mat, out_file) {
    invisible(.Call(`_VCFArrow_write_snmf_cpp`, a1_mat, a2_mat, out_file))
}

write_plink_bed_header_cpp <- function(out_file) {
    invisible(.Call(`_VCFArrow_write_plink_bed_header_cpp`, out_file))
}

write_plink_bed_chunk_cpp <- function(a1_mat, a2_mat, out_file) {
    invisible(.Call(`_VCFArrow_write_plink_bed_chunk_cpp`, a1_mat, a2_mat, out_file))
}

write_plink_ped_cpp <- function(a1_mat, a2_mat, REF, ALT, samples, fid, pat, mat, sex, pheno, out_file) {
    invisible(.Call(`_VCFArrow_write_plink_ped_cpp`, a1_mat, a2_mat, REF, ALT, samples, fid, pat, mat, sex, pheno, out_file))
}

arrow_c_alloc_cpp <- function() {
    .Call(`_VCFArrow_arrow_c_alloc_cpp`)
}

write_vcf_chunk_cpp <- function(output_file, chrom, pos, id, ref, alt, qual, filter_col, info, format_col, fmt_array, fmt_schema, n_samples, gzip = FALSE) {
    invisible(.Call(`_VCFArrow_write_vcf_chunk_cpp`, output_file, chrom, pos, id, ref, alt, qual, filter_col, info, format_col, fmt_array, fmt_schema, n_samples, gzip))
}

