#' @title vcf2arlequin
#'
#' @description
#' Converts a VCFArrow object to an Arlequin infile
#'
#' @author Tomas Hrbek May 2026
#'
#' @param vcf_arrow -> VCFArrow object
#' @param keep_groups -> groups to retain, default NULL (character)
#' @param out_file -> name of file to output, default 'arlequin_infile.arp' (character)
#'
#' @return NULL
#'
#' @details
#' This function converts a VCFArrow object to an external Arlequin formatted file.
#' Writing occurs in chunks whose size is determined by the read_vcf() function.
#' Larger chunks result in faster writing speeds.
#' If no groups are defined, the default behavior is to use all groups.
#'
#' @examples
#' vcf2smartsnp(vcf_arrow = my_vcf, keep_groups = my_groups, out_file = "arlequin_infile.arp")
#' vcf2smartsnp(vcf_arrow, my_groups, out_file = "arlequin_infile.arp")
#' vcf2smartsnp(vcf_arrow)
#'

vcf2arlequin <- function(vcf_arrow, keep_groups = NULL,
                         out_file = "arlequin_infile.arp") {

  if (!inherits(vcf_arrow, "VCFArrow")) {
    cli::cli_abort("Expecting a VCFArrow object")
  }

  all_groups <- vcf_arrow@groups

  # keep all groups if no groups specified
  if (is.null(keep_groups)) {
    keep_groups <- unique(all_groups)
  }

  # define encoder
  value_fn <- function(a1, a2, REF, ALT) {
    allele1 <- ifelse(a1 == 0L, REF, ifelse(a1 == 1L, ALT, "?"))
    allele2 <- ifelse(a2 == 0L, REF, ifelse(a2 == 1L, ALT, "?"))
    return(Map(c, allele1, allele2))
  }

  res <- vcf_build_wide(
    vcf_arrow = vcf_arrow,
    keep_groups = keep_groups,
    value_fn = value_fn,
    n_rows_per_cell = 2
  )

  geno_list <- res$data
  samples <- res$samples
  n_var <- length(res$row_ids)

  groups_keep <- all_groups[all_groups %in% keep_groups]
  group_members <- split(samples, groups_keep)

  con <- file(out_file, open = "wt")
  on.exit(close(con))

  writeLines(c(
    "[Profile]", "",
    "Title = 'Generated by VCFArrow'",
    paste0("NbSamples = ", length(group_members)),
    "GenotypicData = 1",
    "LocusSeparator = WHITESPACE",
    "GameticPhase = 0",
    "MissingData = '?'",
    "DataType = STANDARD", "",
    "[Data]",
    "[[Samples]]", "",
    paste0("#There are ", n_var, " SNPs"), ""
  ), con)

  # buffered writing - reduces syscall overhead
  # estimate total lines once and write in a single buffered call
  n_lines <- sum((2L * lengths(group_members)) + 6L)
  buffer <- character(n_lines)

  idx <- 1L

  for (pop in names(group_members)) {
    inds <- group_members[[pop]]
    buffer[idx] <- paste0("SampleName = '", pop, "'")
    idx <- idx + 1L
    buffer[idx] <- paste0("SampleSize = ", length(inds))
    idx <- idx + 1L
    buffer[idx] <- "SampleData={"
    idx <- idx + 1L

    for (ind in inds) {
      mat <- geno_list[[ind]]
      mat[is.na(mat)] <- "?"
      buffer[idx] <- paste(ind, 1, paste(mat[1L, ], collapse = " "), sep = "\t")
      idx <- idx + 1L
      buffer[idx] <- paste0("\t\t\t\t\t\t", paste(mat[2L, ], collapse = " "))
      idx <- idx + 1L
    }

    buffer[idx] <- "}"
    idx <- idx + 1L

    # blank line between populations
    buffer[idx] <- ""
    idx <- idx + 1L
  }

  writeLines(buffer[seq_len(idx - 1L)], con)

  writeLines(c(
    "[[Structure]]",
    "StructureName = 'One Group'",
    "NbGroups = 1", "",
    "Group = {",
    paste0('\t\t"', names(group_members), '"'),
    "}"
  ), con)

  invisible(vcf_arrow)
}
