#' @title vcf2genepop
#'
#' @description
#' Converts a VCFArrow object to a Genepop format infile
#'
#' @author Tomas Hrbek May 2026
#'
#' @param vcf_arrow -> VCFArrow object
#' @param keep_groups -> groups to retain, default NULL (character)
#' @param out_file -> name of file to output, default 'genepop_infile.gen' (character)
#'
#' @return NULL
#'
#' @details
#' This function converts a VCFArrow object to an external Genpop formatted file.
#' Writing occurs in chunks whose size is determined by the read_vcf() function.
#' Larger chunks result in faster writing speeds.
#' If no groups are defined, the default behavior is to use all groups.
#'
#' @examples
#' vcf2genepop(vcf_arrow = my_vcf, keep_groups = my_groups, out_file = "genepop_infile.gen")
#' vcf2genepop(vcf_arrow, my_groups, out_file = "genepop_infile.gen")
#' vcf2genepop(vcf_arrow)
#'

vcf2genepop <- function(vcf_arrow, keep_groups = NULL,
                        out_file = "genepop_infile.gen") {

  if (!inherits(vcf_arrow, "VCFArrow")) {
    cli::cli_abort("Expecting a VCFArrow object")
  }

  all_groups <- vcf_arrow@groups

  # keep all groups if no groups specified
  if (is.null(keep_groups)) {
    keep_groups <- unique(all_groups)
  }

  # define encoder
  value_fn <- function(a1, a2, REF, ALT) {
    nuc_code <- c(A = "01", C = "02", G = "03", T = "04")
    allele1 <- ifelse(a1 == 0L, REF, ifelse(a1 == 1L, ALT, NA_integer_))
    allele2 <- ifelse(a2 == 0L, REF, ifelse(a2 == 1L, ALT, NA_integer_))
    # numeric encoding
    code1 <- nuc_code[allele1]
    code2 <- nuc_code[allele2]
    # canonical ordering (in principle needed)
    swap <- !is.na(code1) & !is.na(code2) & code1 > code2
    tmp <- code1
    code1[swap] <- code2[swap]
    code2[swap] <- tmp[swap]
    code1[is.na(code1)] <- "00"
    code2[is.na(code2)] <- "00"

    return(paste0(code1, code2))
  }

  res <- vcf_build_wide(
    vcf_arrow = vcf_arrow,
    keep_groups = keep_groups,
    value_fn = value_fn,
    n_rows_per_cell = 1
  )

  geno_list <- res$data
  samples <- res$samples

  # SNP names
  variants <- vcf_arrow@variants %>%
    dplyr::arrange(.row_id) %>%
    dplyr::collect()

  loci <- if (!all(is.na(variants$ID))) {
    variants$ID
  } else {
    paste0(variants$CHROM, "_", variants$POS)
  }

  # population structure
  groups_keep <- all_groups[all_groups %in% keep_groups]
  group_members <- split(samples, groups_keep)

  con <- file(out_file, open = "wt")
  on.exit(close(con))

  # header
  writeLines("Title = 'Generated by VCFArrow'", con)
  writeLines(paste(loci, collapse = ", "), con)

  for (pop in names(group_members)) {
    writeLines(paste0("pop ", pop), con)
    inds <- group_members[[pop]]
    n_ind <- length(inds)

    # buffered writing - reduces syscall overhead
    buffer <- character(n_ind)
    for (i in seq_len(n_ind)) {
      ind <- inds[i]
      vec <- geno_list[[ind]]
      # ensure missing handled
      vec[is.na(vec)] <- "0000"
      buffer[i] <- paste(ind, paste(vec, collapse = " "), sep = ", ")
    }
    writeLines(buffer, con)
  }

  invisible(vcf_arrow)
}
